### ISSUE TITLE
Error print leads to spurious panics

### ISSUE THREAD

**Issue by nkrackow** [quartiq/stabilizer#654]
https://github.com/quartiq/stabilizer/blob/e8116b34a254073bbfb0e7b163989f34af5504e6/src/hardware/driver/mod.rs#L107-L110
Under certain timing circumstances this error print takes too long and the firmware panics because the Stabilizer adc dma isn't handled fast enaugh. I would like to keep this print so I'll have to move it somewhere where it doesn't block the dsp task.

**Comment by ryan-summers** [comment]
I'm somewhat confused why this would be happening. We take explicit steps to ensure that ISRs are not disabled during log printing/formatting.

The only reason this could be causing a panic would be if the `laser_interlock` (or something outside of it) has elevated the ceiling ISR priority to that equivalent of the DMA ISR. What's the ISR ceiling in the middle of that call? Is something elevating the priority ceiling somehow that isn't clear?

I can't see anything immediately in main, but that's what I would expect to be the root cause. Formatting can take some time, but the DMA process _should_ be able to interrupt the formatting. Something seems like it's not allowing the DMA to interrupt

**Comment by ryan-summers** [comment]
We explicitly update logging to not use critical sections: https://github.com/quartiq/stabilizer/blob/master/src/hardware/setup.rs#L228

**Comment by nkrackow** [comment]
I've revisited this now and I understand your point @ryan-summers. I sometimes get an ADC FIFO overflow when I uncomment the error print and trigger an interrupt condition. This should not happen since the `process` task with the ADC handling is higher priority and should interrupt the logging.

**Comment by nkrackow** [comment]
Anyways, since Driver development is further along now and the mqtt interlock reporting looks good with the same info as the error log I think we don't need it any more and I'll close this.
