### ISSUE TITLE
serial settings `list` should skip repeating default if equal

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#864]
`/dual_iir/iir_ch/0/0: {"ba":[1.0,0.0,0.0,0.0,0.0],"u":0.0,"min":-32767.0,"max":32767.0} [default: {"ba":[1.0,0.0,0.0,0.0,0.0],"u":0.0,"min":-32767.0,"max":32767.0}]`

In the case where they are default, just say

`/dual_iir/iir_ch/0/0: {"ba":[1.0,0.0,0.0,0.0,0.0],"u":0.0,"min":-32767.0,"max":32767.0} [default]`

**Comment by ryan-summers** [comment]
I took a look at this yesterday because I was thinking the same. The main issue with implementation is that we only have a single copy in memory at a time (i.e. either the default version, or the current value. We can't compare them because as soon as we're done with one,  we erase it to format the next.

**Comment by ryan-summers** [comment]
Maybe some PartialEq implementation could help, but we don't know the concrete type of the settings in `serial-settings`, so we are operating with the JSON-formatted version

**Comment by jordens** [comment]
It's a nice-to-have.
Maybe just split the serialize buffer for this?

**Comment by jordens** [comment]
Or hash each after serialization.
