### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#9]
Some preliminary characterization results of firmware and hardware

![image](https://user-images.githubusercontent.com/1338946/58821071-88059780-8634-11e9-8265-75612323ec3a.png)
![image](https://user-images.githubusercontent.com/1338946/58821124-b4211880-8634-11e9-967b-9067ead8f238.png)

**Comment by hartytp** [comment]
Testing from Sampler (same ADC) https://github.com/sinara-hw/Sampler/issues/2

for G=1, terminated inputs noise was 1.8 LSB RMS. From above data, noise on stabilizer ADCs with G=1 was 1.8LSB RMS. So, consistent, which is good! (Can't remember what we expect off the top of my head, since Stabilizer might has slightly different input filters IIRC).

@jordens Was the above with PoE or the 12V supply? Did you test both/observe any differences between the two?

**Comment by jordens** [comment]
I think that was Poe. Not entirely sure. The 125 khz peak feels like typical Poe behavior. Poe had quite some ground noise injected. See the other issue on the hardware I filed.
